version: "3.9"
services:
  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./data:/app/data
    networks: [app]
  frontend:
    build: ./frontend
    env_file: .env
    depends_on: [backend]
    networks: [app]
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [frontend]
    ports: ["3000:443"]
    networks: [app]
networks:
  app:
